/*
 * Root build.gradle - minimal for Gradle 8.5 + Java 21
 * Java 8 bytecode target via sourceCompatibility/targetCompatibility
 */
apply plugin: 'base'

subprojects {
    apply plugin: 'java'
    repositories { mavenCentral() }
    [compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
    compileJava {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    configurations.all {
        if (name == 'compile') { transitive = true }
    }
}

// Subproject dependency wiring
subprojects { sub ->
    afterEvaluate {
        if (sub.name == 'HMCLAPI') {
            sub.dependencies {
                implementation 'com.google.code.gson:gson:2.2.4'
            }
        }
        if (sub.name == 'HMCLCore') {
            sub.dependencies {
                implementation project(':HMCLAPI')
                implementation 'com.google.code.gson:gson:2.2.4'
                implementation 'org.commonjava.googlecode.markdown4j:markdown4j:2.2-cj-1.0'
            }
        }
        if (sub.name == 'HMCLaF') {
            sub.dependencies { implementation project(':HMCLCore') }
        }
        if (sub.name == 'HMCL') {
            sub.dependencies {
                implementation project(':HMCLaF')
                implementation project(':HMCLAPI')
                implementation project(':HMCLCore')
            }
        }
    }
}
