name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 8.5
          java-version: 21
          distribution: temurin

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew assemble -x test

      - name: Upload HMCL jar
        if: success()
        uses: actions/upload-artifact@v5
        with:
          name: HMCL-jar
          path: HMCL/build/libs/*.jar
          retention-days: 7
